FROM openjdk:8-jre
MAINTAINER Mr.王
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
WORKDIR /
COPY target/helloworld-0.0.1-SNAPSHOT.jar /
EXPOSE 8072
CMD java -jar helloworld-0.0.1-SNAPSHOT.jar